import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F0281CB6-CF26-4053-9936-96D7EE602E5E),
	
	helpstring("IADSExplorerShellFolder Interface"),
	pointer_default(unique)
]
interface IADSExplorerShellFolder : IUnknown
{
};

[
	object,
	uuid(E4C5A47C-D60F-4E81-A418-06C382F65D30),
	
	helpstring("IADSXContextMenuEntry Interface"),
	pointer_default(unique)
]
interface IADSXContextMenuEntry : IUnknown
{
};

[
	uuid(72B8106C-7E36-4E68-B125-53C535BC4A9F),
	version(1.0),
	helpstring("ADSExplorer 1.0 Type Library")
]
library ADSEXPLORERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(ED383D11-6797-4103-85EF-CBDB8DEB50E2),
		helpstring("ADSExplorerShellFolder Class")
	]
	coclass ADSExplorerShellFolder
	{
		[default] interface IADSExplorerShellFolder;
	};
	
	[
		uuid(D8AECA1A-7E1D-44C2-ABB0-F0558AB00092),
		helpstring("ADSXContextMenuEntry Class")
	]
	coclass ADSXContextMenuEntry
	{
		[default] interface IADSXContextMenuEntry;
	};
};
